<a href="https://colab.research.google.com/github/Dmytro-Kruhlov/HomeWork_DataScience/blob/main/HW_DS_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
import matplotlib.pyplot as plt


Напишіть функцію гіпотези лінійної регресії у векторному вигляді;

In [4]:
df = pd.read_csv("/content/Housing.csv")
print(df[df.isna()].count())
print(df.describe())
df

price               0
area                0
bedrooms            0
bathrooms           0
stories             0
mainroad            0
guestroom           0
basement            0
hotwaterheating     0
airconditioning     0
parking             0
prefarea            0
furnishingstatus    0
dtype: int64
              price          area    bedrooms   bathrooms     stories  \
count  5.450000e+02    545.000000  545.000000  545.000000  545.000000   
mean   4.766729e+06   5150.541284    2.965138    1.286239    1.805505   
std    1.870440e+06   2170.141023    0.738064    0.502470    0.867492   
min    1.750000e+06   1650.000000    1.000000    1.000000    1.000000   
25%    3.430000e+06   3600.000000    2.000000    1.000000    1.000000   
50%    4.340000e+06   4600.000000    3.000000    1.000000    2.000000   
75%    5.740000e+06   6360.000000    3.000000    2.000000    2.000000   
max    1.330000e+07  16200.000000    6.000000    4.000000    4.000000   

          parking  
count  545.000000  
mea

price  area  bedrooms  bathrooms  stories mainroad guestroom basement  \
0    13300000  7420         4          2        3      yes        no       no   
1    12250000  8960         4          4        4      yes        no       no   
2    12250000  9960         3          2        2      yes        no      yes   
3    12215000  7500         4          2        2      yes        no      yes   
4    11410000  7420         4          1        2      yes       yes      yes   
..        ...   ...       ...        ...      ...      ...       ...      ...   
540   1820000  3000         2          1        1      yes        no      yes   
541   1767150  2400         3          1        1       no        no       no   
542   1750000  3620         2          1        1      yes        no       no   
543   1750000  2910         3          1        1       no        no       no   
544   1750000  3850         3          1        2      yes        no       no   

    hotwaterheating airconditioning  parking prefarea furnishingstatus  
0                no             yes        2      yes        furnished  
1                no             yes        3       no        furnished  
2                no              no        2      yes   semi-furnished  
3                no             yes        3      yes        furnished  
4                no             yes        2       no        furnished  
..              ...             ...      ...      ...              ...  
540              no              no        2       no      unfurnished  
541              no              no        0       no   semi-furnished  
542              no              no        0       no      unfurnished  
543              no              no        0       no        furnished  
544              no              no        0       no      unfurnished  

[545 rows x 13 columns]

In [153]:
x_col = ["area", "bedrooms","bathrooms"]
y_col = "price"
data = [y_col] + x_col
df_view = df[data]
df_view

price  area  bedrooms  bathrooms
0    13300000  7420         4          2
1    12250000  8960         4          4
2    12250000  9960         3          2
3    12215000  7500         4          2
4    11410000  7420         4          1
..        ...   ...       ...        ...
540   1820000  3000         2          1
541   1767150  2400         3          1
542   1750000  3620         2          1
543   1750000  2910         3          1
544   1750000  3850         3          1

[545 rows x 4 columns]

In [169]:
x_data = df[x_col].values
print(x_data.shape)
print(x_data)
y_data = df[y_col].values.reshape(-1, 1)
print(y_data.shape)
weight = np.zeros(3).reshape(-1, 1)
print(weight.reshape(-1, 1).shape)
learning_rate = 0.0000000001
num_iterations = 50



(545, 3)
[[7420    4    2]
 [8960    4    4]
 [9960    3    2]
 ...
 [3620    2    1]
 [2910    3    1]
 [3850    3    1]]
(545, 1)
(3, 1)


In [155]:
def hypothesis(w, X):
  return np.dot(X, w)

In [156]:
hyp = hypothesis(weight, x_data)
hyp.shape

(545, 1)

Створіть функцію для обчислення функції втрат у векторному вигляді;

In [157]:
def loss_fuction(w, X, y):
    m = len(y)
    predictions = hypothesis(w, X)
    cost = (1/(2*m)) * np.sum(np.square(predictions - y))
    return cost

In [158]:
loss = loss_fuction(weight, x_data, y_data)
print(loss)

13106916364659.268


Реалізуйте один крок градієнтного спуску;

In [159]:
def gradient_descent_step(w, X, y, learning_rate):
    m = len(y)
    predictions = hypothesis(w, X)
    errors = predictions - y
    gradient = (1/m) * np.dot(X.T, errors)

    w = w - (learning_rate * gradient)
    return w


In [160]:
step = gradient_descent_step(weight, x_data, y_data, learning_rate)
print(step)

[[2.67229201e+08]
 [1.46390263e+05]
 [6.61666767e+04]]


Знайдіть найкращі параметри $\vec{w}$ для датасету прогнозуючу ціну на будинок залежно від площі, кількості ванних кімнат та кількості спалень;

In [161]:
def gradient_descent(X, y, w, learning_rate, num_iterations):

    losses = []
    for _ in range(num_iterations):
        losses.append(loss_fuction(w, X, y))
        w = gradient_descent_step(w, X, y, learning_rate)
    print(losses)
    return w

In [171]:
optimal_w = gradient_descent(x_data, y_data, weight, learning_rate, num_iterations)
print(optimal_w.shape)
optimal_w

[13106916364659.268, 13035616398533.447, 12964761061748.393, 12894347581578.36, 12824373202588.434, 12754835186526.701, 12685730812217.086, 12617057375452.877, 12548812188890.896, 12480992581946.35, 12413595900688.305, 12346619507735.844, 12280060782154.871, 12213917119355.516, 12148185930990.25, 12082864644852.576, 12017950704776.367, 11953441570535.855, 11889334717746.215, 11825627637764.783, 11762317837592.889, 11699402839778.299, 11636880182318.264, 11574747418563.182, 11513002117120.852, 11451641861761.328, 11390664251322.365, 11330066899615.469, 11269847435332.494, 11210003501952.873, 11150532757651.39, 11091432875206.543, 11032701541909.47, 10974336459473.453, 10916335343943.979, 10858695925609.361, 10801415948911.928, 10744493172359.742, 10687925368438.91, 10631710323526.389, 10575845837803.38, 10520329725169.24, 10465159813155.936, 10410333942843.025, 10355849968773.176, 10301705758868.21, 10247899194345.684, 10194428169635.941, 10141290592299.758, 10088484382946.436]
(3, 1)


array([[1.23884209e+02],
       [6.83609762e-02],
       [3.09534280e-02]])

Знайдіть ці ж параметри за допомогою аналітичного рішення;

In [172]:
def analytical_solution(X, y):
    return np.linalg.inv(X.T @ X) @ X.T @ y

In [173]:
analytical_solution = analytical_solution(x_data, y_data)
analytical_solution

array([[3.72448352e+02],
       [3.68974672e+05],
       [1.37031315e+06]])

Порівняйте отримані результати.

In [174]:
print(optimal_w)
print(analytical_solution)

[[1.23884209e+02]
 [6.83609762e-02]
 [3.09534280e-02]]
[[3.72448352e+02]
 [3.68974672e+05]
 [1.37031315e+06]]
