<a href="https://colab.research.google.com/github/Dmytro-Kruhlov/HomeWork_DataScience/blob/main/HW_DS_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
import matplotlib.pyplot as plt


Напишіть функцію гіпотези лінійної регресії у векторному вигляді;

In [4]:
df = pd.read_csv("/content/Housing.csv")
print(df[df.isna()].count())
print(df.describe())
df

price               0
area                0
bedrooms            0
bathrooms           0
stories             0
mainroad            0
guestroom           0
basement            0
hotwaterheating     0
airconditioning     0
parking             0
prefarea            0
furnishingstatus    0
dtype: int64
              price          area    bedrooms   bathrooms     stories  \
count  5.450000e+02    545.000000  545.000000  545.000000  545.000000   
mean   4.766729e+06   5150.541284    2.965138    1.286239    1.805505   
std    1.870440e+06   2170.141023    0.738064    0.502470    0.867492   
min    1.750000e+06   1650.000000    1.000000    1.000000    1.000000   
25%    3.430000e+06   3600.000000    2.000000    1.000000    1.000000   
50%    4.340000e+06   4600.000000    3.000000    1.000000    2.000000   
75%    5.740000e+06   6360.000000    3.000000    2.000000    2.000000   
max    1.330000e+07  16200.000000    6.000000    4.000000    4.000000   

          parking  
count  545.000000  
mea

price  area  bedrooms  bathrooms  stories mainroad guestroom basement  \
0    13300000  7420         4          2        3      yes        no       no   
1    12250000  8960         4          4        4      yes        no       no   
2    12250000  9960         3          2        2      yes        no      yes   
3    12215000  7500         4          2        2      yes        no      yes   
4    11410000  7420         4          1        2      yes       yes      yes   
..        ...   ...       ...        ...      ...      ...       ...      ...   
540   1820000  3000         2          1        1      yes        no      yes   
541   1767150  2400         3          1        1       no        no       no   
542   1750000  3620         2          1        1      yes        no       no   
543   1750000  2910         3          1        1       no        no       no   
544   1750000  3850         3          1        2      yes        no       no   

    hotwaterheating airconditioning  parking prefarea furnishingstatus  
0                no             yes        2      yes        furnished  
1                no             yes        3       no        furnished  
2                no              no        2      yes   semi-furnished  
3                no             yes        3      yes        furnished  
4                no             yes        2       no        furnished  
..              ...             ...      ...      ...              ...  
540              no              no        2       no      unfurnished  
541              no              no        0       no   semi-furnished  
542              no              no        0       no      unfurnished  
543              no              no        0       no        furnished  
544              no              no        0       no      unfurnished  

[545 rows x 13 columns]

In [153]:
x_col = ["area", "bedrooms","bathrooms"]
y_col = "price"
data = [y_col] + x_col
df_view = df[data]
df_view

price  area  bedrooms  bathrooms
0    13300000  7420         4          2
1    12250000  8960         4          4
2    12250000  9960         3          2
3    12215000  7500         4          2
4    11410000  7420         4          1
..        ...   ...       ...        ...
540   1820000  3000         2          1
541   1767150  2400         3          1
542   1750000  3620         2          1
543   1750000  2910         3          1
544   1750000  3850         3          1

[545 rows x 4 columns]

In [195]:
x_data = df[x_col].values
ones_column = np.ones((x_data.shape[0], 1))
x_data_with_bias = np.hstack((ones_column, x_data))
print(x_data.shape)
print(x_data)
y_data = df[y_col].values.reshape(-1, 1)
print(y_data.shape)
weight = np.zeros(4).reshape(-1, 1)
print(weight.reshape(-1, 1).shape)
learning_rate = 0.00000001
num_iterations = 100



(545, 3)
[[7420    4    2]
 [8960    4    4]
 [9960    3    2]
 ...
 [3620    2    1]
 [2910    3    1]
 [3850    3    1]]
(545, 1)
(4, 1)


In [155]:
def hypothesis(w, X):
  return np.dot(X, w)

In [182]:
hyp = hypothesis(weight, x_data_with_bias)
hyp.shape

(545, 1)

Створіть функцію для обчислення функції втрат у векторному вигляді;

In [157]:
def loss_fuction(w, X, y):
    m = len(y)
    predictions = hypothesis(w, X)
    cost = (1/(2*m)) * np.sum(np.square(predictions - y))
    return cost

In [183]:
loss = loss_fuction(weight, x_data_with_bias, y_data)
print(loss)

13106916364659.268


Реалізуйте один крок градієнтного спуску;

In [159]:
def gradient_descent_step(w, X, y, learning_rate):
    m = len(y)
    predictions = hypothesis(w, X)
    errors = predictions - y
    gradient = (1/m) * np.dot(X.T, errors)

    w = w - (learning_rate * gradient)
    return w


In [184]:
step = gradient_descent_step(weight, x_data_with_bias, y_data, learning_rate)
print(step)

[[4.76672925e-04]
 [2.67229201e+00]
 [1.46390263e-03]
 [6.61666767e-04]]


Знайдіть найкращі параметри $\vec{w}$ для датасету прогнозуючу ціну на будинок залежно від площі, кількості ванних кімнат та кількості спалень;

In [175]:
def gradient_descent(X, y, weight, learning_rate, num_iterations):

    losses = []
    for _ in range(num_iterations):
        losses.append(loss_fuction(w, X, y))
        w = gradient_descent_step(w, X, y, learning_rate)
    print(losses)
    return w

In [196]:
optimal_w = gradient_descent(x_data_with_bias, y_data, weight, learning_rate, num_iterations)
print(optimal_w.shape)
optimal_w

[13106916364659.268, 7080821888985.328, 4230806738074.512, 2882904471305.3086, 2245419951067.832, 1943924410031.2297, 1801333393403.7786, 1733895579532.428, 1702001145596.2961, 1686916798401.5002, 1679782708519.4958, 1676408658208.5042, 1674812902236.8464, 1674058182828.125, 1673701227998.9504, 1673532394195.324, 1673452531411.423, 1673414747083.814, 1673396863578.848, 1673388392081.279, 1673384371951.618, 1673382457077.0232, 1673381537873.643, 1673381089568.6284, 1673380863972.9453, 1673380743706.6711, 1673380673255.483, 1673380626364.122, 1673380590615.2812, 1673380560136.2458, 1673380532149.5432, 1673380505341.5786, 1673380479091.0938, 1673380453104.2676, 1673380427242.1372, 1673380401438.9822, 1673380375663.7197, 1673380349901.6494, 1673380324145.8188, 1673380298392.9395, 1673380272641.4573, 1673380246890.6355, 1673380221140.1272, 1673380195389.7673, 1673380169639.478, 1673380143889.2231, 1673380118138.9849, 1673380092388.7546, 1673380066638.529, 1673380040888.3062, 1673380015138.0

array([[5.00489960e-01],
       [8.55708799e+02],
       [1.78793754e+00],
       [9.54527117e-01]])

Знайдіть ці ж параметри за допомогою аналітичного рішення;

In [197]:
def analytical_solution(X, y):
    return np.linalg.inv(X.T @ X) @ X.T @ y

In [198]:
analytical_solution = analytical_solution(x_data_with_bias, y_data)
analytical_solution

array([[-1.73171608e+05],
       [ 3.78762754e+02],
       [ 4.06820034e+05],
       [ 1.38604950e+06]])

Порівняйте отримані результати.

In [199]:
print(optimal_w)
print(analytical_solution)

[[5.00489960e-01]
 [8.55708799e+02]
 [1.78793754e+00]
 [9.54527117e-01]]
[[-1.73171608e+05]
 [ 3.78762754e+02]
 [ 4.06820034e+05]
 [ 1.38604950e+06]]
